// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:main.Task):Promise<void>;

export function CheckUpdate():Promise<main.CheckUpdateResult>;

export function DeleteAnnualData(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetAllAnnualData():Promise<main.SystemData>;

export function GetAnnualData(arg1:string):Promise<main.AnnualData>;

export function GetAvatarAbsolutePath(arg1:string):Promise<string>;

export function GetLastUsedAccount():Promise<main.Account>;

export function Greet(arg1:string):Promise<string>;

export function NewAccount(arg1:string,arg2:string):Promise<main.Account>;

export function OpenDownloadURL(arg1:string):Promise<void>;

export function ResetAllData():Promise<void>;

export function SaveAccount(arg1:main.Account):Promise<void>;

export function SaveAnnualData(arg1:main.AnnualData):Promise<void>;

export function SwitchAccount(arg1:string):Promise<void>;

export function UpdateTask(arg1:main.Task):Promise<void>;
