// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function DeleteAnnualData(arg1) {
  return window['go']['main']['App']['DeleteAnnualData'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAllAnnualData() {
  return window['go']['main']['App']['GetAllAnnualData']();
}

export function GetAnnualData(arg1) {
  return window['go']['main']['App']['GetAnnualData'](arg1);
}

export function GetAvatarAbsolutePath(arg1) {
  return window['go']['main']['App']['GetAvatarAbsolutePath'](arg1);
}

export function GetLastUsedAccount() {
  return window['go']['main']['App']['GetLastUsedAccount']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function NewAccount(arg1, arg2) {
  return window['go']['main']['App']['NewAccount'](arg1, arg2);
}

export function OpenDownloadURL(arg1) {
  return window['go']['main']['App']['OpenDownloadURL'](arg1);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function SaveAccount(arg1) {
  return window['go']['main']['App']['SaveAccount'](arg1);
}

export function SaveAnnualData(arg1) {
  return window['go']['main']['App']['SaveAnnualData'](arg1);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}
